import type { Metadata } from 'next'
import Script from 'next/script'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

type Props = {
  children: ReactNode
}

export default function RestaurantsLayout({ children }: Props): JSX.Element {
  return (
    <>
      <Script
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}&libraries=places`}
      />
      {children}
    </>
  )
}
